#!/bin/bash
#
# FILE
#	gitwrap
#
# DESCRIPTION
#	Example shell wrapper for git.
#
#	This shell script sets up the environment for the invocation of 
#	wrapper.rb.  
#	
# NOTES
#	Needs to be installed as 'git' for use with SourceTree git client, 
#	but can live anywhere in your PATH.
#
# AUTHOR
#	L. Cliff Brett 2/2012
#

. ~/.bashrc
wrap_yaml=~/.gitwrap.yaml

# Restore quotes to args as appropriate:
#   	We assume that any arg that includes whitespace should be quoted.
#   	The only exception is the --format option, whose argument is a format
#	string.  The format string should be quoted alone; e.g.,
#		
#		--format="<format string>"
#
#	The shell wants to strip these quotes off before passing them to wrapper.rb,
#	and I haven't figured a way around it.  We therefore also insert '%q' or '%Q',
#	which wrapper.rb will replace with quotes.
#
#	We also need to escape '<' and '>' with a '\' character.
#
args=""
until [ $# == 0 ]; do
   arg=`echo $1 | sed -E 's/([\<\>])/\\\&/g; s/(--format=)?(.+[ ]+.+)/\1\\\"%q\\2\%q\\\"/g'`
   args="$args $arg"
   shift 1
done

# Invoke 'wrapper.rb' with args.
cmd="/bin/bash -c \"WRAP_YAML=$wrap_yaml wrapper.rb $args\""
eval $cmd
exit $?
