#!/bin/bash
#
# FILE
#	testwrap
#
# DESCRIPTION
#	Test wrapper.rb.
#
#	This shell script sets up the environment for the invocation of 
#	wrapper.rb.  Useful for testing.
#
# NOTES
#	Put this file somewhere in your PATH.
#	
# AUTHOR
#	L. Cliff Brett 2/2012
#

. ~/.bashrc
wrap_yaml=~/.testwrap.yaml

# Restore quotes to args as appropriate:
#   	We assume that any arg that includes whitespace should be quoted.
#   	The only exception is the --format option, whose argument is a format
#	string.  The format string should be quoted alone; e.g.,
#		
#		--format="<format string>"
#
#	We also need to escape '<' and '>' with a '\' character.
#
args=""
until [ $# == 0 ]; do
   arg=`echo $1 | sed -E 's/([\<\>])/\\\&/g; s/(--format=)?(.+[ ]+.+)/\1\\\"\2\\\"/g'`
   echo "ARG = $arg"
   args="$args $arg"
   shift 1
done

# Invoke 'wrapper.rb' with args.
cmd="/bin/bash -c \"WRAP_YAML=$wrap_yaml wrapper.rb $args\""
echo $cmd
eval $cmd
exit $?
